### ISSUE TITLE
zephyr: GATT/SR/GAN/BV-02-C: random PASS

### ISSUE THREAD

**Issue by mkasenberg** [auto-pts/auto-pts#970]
~~Since PTS 8.5.0~~ the test case randomly finishes with PASS, BTP TIMEOUT or INCONC, If LT2 fails before LT1, than bot falls into an unrecoverable state.

**Comment by mkasenberg** [comment]
Sometimes happens this exception:
```python
2023-07-12 13:18:34,683 root ERROR client.py                 192   on_implicit_send          : OnImplicitSend caught exception bad char in struct format
Traceback (most recent call last):
  File "C:\Users\Codecoup\auto-pts\autopts\client.py", line 185, in on_implicit_send
    testcase_response = RUNNING_TEST_CASE[test_case_name].on_implicit_send(project_name, wid, test_case_name,
  File "C:\Users\Codecoup\auto-pts\autopts\ptsprojects\testcase.py", line 693, in on_implicit_send
    my_response = self.handle_mmi_generic(wid, description, style,
  File "C:\Users\Codecoup\auto-pts\autopts\ptsprojects\testcase.py", line 642, in handle_mmi_generic
    response = self.generic_wid_hdl(wid, description, test_case_name)
  File "C:\Users\Codecoup/noahlink/ext-nlw-test/autopts_nlw_project\ptsprojects\nlw\gatt_wid.py", line 30, in gatt_wid_hdl
    return generic_wid_hdl(wid, description, test_case_name, [__name__, 'autopts.wid.gatt'])
  File "C:\Users\Codecoup\auto-pts\autopts\wid\wid.py", line 31, in generic_wid_hdl
    return _generic_wid_hdl(wid, description, test_case_name, module_names)
  File "C:\Users\Codecoup\auto-pts\autopts\wid\wid.py", line 24, in _generic_wid_hdl
    return wid_hdl(WIDParams(wid, description, test_case_name))
  File "C:\Users\Codecoup\auto-pts\autopts\wid\gatt.py", line 1101, in hdl_wid_93
    db = gatt_server_fetch_db().db
  File "C:\Users\Codecoup\auto-pts\autopts\wid\gatt.py", line 97, in gatt_server_fetch_db
    prop, value_handle, uuid = struct.unpack("<BH%ds" % uuid_len, val)
struct.error: bad char in struct format
```

sometimes this one:
```python
2023-07-09 10:42:52,163 root ERROR client.py                 192   on_implicit_send          : OnImplicitSend caught exception Invalid opcode 0x1c in the response, expected 0x1d!
Traceback (most recent call last):
  File "C:\Users\Codecoup\auto-pts\autopts\client.py", line 185, in on_implicit_send
    testcase_response = RUNNING_TEST_CASE[test_case_name].on_implicit_send(project_name, wid, test_case_name,
  File "C:\Users\Codecoup\auto-pts\autopts\ptsprojects\testcase.py", line 693, in on_implicit_send
    my_response = self.handle_mmi_generic(wid, description, style,
  File "C:\Users\Codecoup\auto-pts\autopts\ptsprojects\testcase.py", line 642, in handle_mmi_generic
    response = self.generic_wid_hdl(wid, description, test_case_name)
  File "C:\Users\Codecoup\auto-pts\autopts\ptsprojects\zephyr\gatt_wid.py", line 25, in gatt_wid_hdl
    return generic_wid_hdl(wid, description, test_case_name, [__name__, 'autopts.wid.gatt'])
  File "C:\Users\Codecoup\auto-pts\autopts\wid\wid.py", line 31, in generic_wid_hdl
    return _generic_wid_hdl(wid, description, test_case_name, module_names)
  File "C:\Users\Codecoup\auto-pts\autopts\wid\wid.py", line 24, in _generic_wid_hdl
    return wid_hdl(WIDParams(wid, description, test_case_name))
  File "C:\Users\Codecoup\auto-pts\autopts\wid\gatt.py", line 2002, in hdl_wid_308
    db = gatt_server_fetch_db().db
  File "C:\Users\Codecoup\auto-pts\autopts\wid\gatt.py", line 77, in gatt_server_fetch_db
    attr_val = btp.gatts_get_attr_val(bd_addr_type, bd_addr, handle)
  File "C:\Users\Codecoup\auto-pts\autopts\pybtp\btp\gatt.py", line 464, in gatts_get_attr_val
    btp_hdr_check(tuple_hdr, defs.BTP_SERVICE_ID_GATT,
  File "C:\Users\Codecoup\auto-pts\autopts\pybtp\btp\btp.py", line 347, in btp_hdr_check
    raise BTPError(
autopts.pybtp.types.BTPError: Invalid opcode 0x1c in the response, expected 0x1d!
```

sometimes this one:
```python
2023-07-09 10:45:34,157 root ERROR client.py                 192   on_implicit_send          : OnImplicitSend caught exception bytes is not a 16-char string
Traceback (most recent call last):
  File "C:\Users\Codecoup\auto-pts\autopts\client.py", line 185, in on_implicit_send
    testcase_response = RUNNING_TEST_CASE[test_case_name].on_implicit_send(project_name, wid, test_case_name,
  File "C:\Users\Codecoup\auto-pts\autopts\ptsprojects\testcase.py", line 693, in on_implicit_send
    my_response = self.handle_mmi_generic(wid, description, style,
  File "C:\Users\Codecoup\auto-pts\autopts\ptsprojects\testcase.py", line 642, in handle_mmi_generic
    response = self.generic_wid_hdl(wid, description, test_case_name)
  File "C:\Users\Codecoup\auto-pts\autopts\ptsprojects\zephyr\gatt_wid.py", line 25, in gatt_wid_hdl
    return generic_wid_hdl(wid, description, test_case_name, [__name__, 'autopts.wid.gatt'])
  File "C:\Users\Codecoup\auto-pts\autopts\wid\wid.py", line 31, in generic_wid_hdl
    return _generic_wid_hdl(wid, description, test_case_name, module_names)
  File "C:\Users\Codecoup\auto-pts\autopts\wid\wid.py", line 24, in _generic_wid_hdl
    return wid_hdl(WIDParams(wid, description, test_case_name))
  File "C:\Users\Codecoup\auto-pts\autopts\wid\gatt.py", line 1101, in hdl_wid_93
    db = gatt_server_fetch_db().db
  File "C:\Users\Codecoup\auto-pts\autopts\wid\gatt.py", line 98, in gatt_server_fetch_db
    uuid = btp.btp2uuid(uuid_len, uuid)
  File "C:\Users\Codecoup\auto-pts\autopts\pybtp\btp\btp.py", line 597, in btp2uuid
    return UUID(bytes=uu[::-1]).urn[9:].replace('-', '').upper()
  File "C:\Users\Codecoup\AppData\Local\Programs\Python\Python39\lib\uuid.py", line 186, in __init__
    raise ValueError('bytes is not a 16-char string')
ValueError: bytes is not a 16-char string
```
